### ISSUE TITLE
LOVE IT!!! FIVE STARS *****

### ISSUE THREAD

**Issue by inglesuniversal** [NativeScript/playground-feedback#100]
I love NativeScript!

I have attended several seminars and the more I use it... the more I fall in LOVE

One quick and simple question: How to force the keyboard on iOS to enter a username ALL in lowercase instead of having to press SHIFT first on the keyboard to disable CAPS.

Regards

**Comment by radeva** [comment]
@inglesuniversal Have you tried https://docs.nativescript.org/api-reference/modules/_ui_enums_.autocapitalizationtype ?

**Comment by radeva** [comment]
I'm closing this issue since it is not related to any feedback regarding NativeScript Playground. For any general NativeScript support, please use [Slack](https://developer.telerik.com/wp-login.php?action=slack-invitation) or [StackOverflow](https://stackoverflow.com/tags/nativescript).
