### ISSUE TITLE
Make Scan QR Code Big and Easily Accessible In Playground App

### ISSUE THREAD

**Issue by rakeshgirase** [NativeScript/playground-feedback#104]
## Please, provide the details below:
It would be great if Scan QR Code button is made big, in the center to make it easily reachable and accessible as that is the only button which would be used for 99% of the time when the app is used in both ios and android app.

**Comment by radeva** [comment]
@rakeshgirase Thanks for your suggestion! Isn't it that you scan the first time and then the app refreshes out of the box on every change? It would help if you visualise your idea, even if it is on paper

**Comment by rakeshgirase** [comment]
Something like this. 
![new scan button](https://user-images.githubusercontent.com/16098644/49345224-bbfa0300-f679-11e8-8438-0fe7dfe3953a.jpg)

**Comment by vhristov5555** [comment]
We have deploy a new version in which we have addressed this issue.
