### ISSUE TITLE
Projects tab is always empty.

### ISSUE THREAD

**Issue by udaysasigadgets** [NativeScript/playground-feedback#113]
I am trying to evaluate ReactNative and NativeScript for an app I have in mind. I started looking at NativeScript and found the Playground app very useful for quick prototyping. However I ran into an issue where explicit saving of a project (Clicking on Save, I am not talking about Cmd+S) does save my project and gives me a new url with the version bumped up. However when I go to the "Projects" tab, I see nothing but this message: 

> You don't have any saved projects yet.
> When you save your project it will appear here and you can return to your code at any time.

I have been playing with Playground and NativeScript on the whole for only a day, did save many projects many times, however none show up in Projects tab. I have to manually save my URL (or remember my version number) so I can come back later to start where I left off. 

I am running Chrome. I tried incognito in Chrome - same problem. Can never see "My Projects". I even tried Safari. So, I am beginning to think this is not a browser issue. Is this a bug?

Hope someone can get back to me. Its a huge inconvenience to manually save URLs in a text file :)

-Uday

**Comment by vhristov5555** [comment]
Hi, 

Sorry for the wait response. 

There are two different behaviours when you are saving sessions for first time:
- When you are not log in: If you have saved the first version as anonymous user and after that log in and save again the saved session won't be visible in you account. In this case you need to fork the project in you account.
- When you are logged in: If you have saved session it will appear in you account (or forked)

Hope this helps.

Best Regards,
Vasil Hristov
