### ISSUE TITLE
Groceries Register/SignUp needs validation

### ISSUE THREAD

**Issue by VoroDk** [NativeScript/playground-feedback#116]
In step 12/20  where you first make the register and in step 14/20  where you remake it, doesn't validate user input, and gives you the "Your account was successfully created" Alert, even though the fields are empty.

Shouldn't there be an empty check in the tutorial?

**Comment by tjvantoll** [comment]
Thanks @VoroDk for pointing this out. We chose to leave the validation to the backend for simplicity (the tutorial is a bit long as is), BUT, I never realized that the Kinvey registration API has some, well, interesting behavior. Apparently, if you pass the registration API an empty email and password it creates a user with a generated user name and password, which is not what I expected at all, and is why you see the “Your account was successfully created” alert.

I’ll go ahead and add a bit of validation to address this. Thanks again!
