### ISSUE TITLE
QR Code scanner shows very blurry image

### ISSUE THREAD

**Issue by MuhAssar** [NativeScript/playground-feedback#122]
when I tap on the scan button in {N} Playground,
the camera viewfinder shows a blurry and out-of-focus image, and it can't recognize or read the QR Code properly.
and I have 3 other camera apps on my device, and all of them show sharp and clear image of the QR Code
I even managed to use another QR Code scanner to scan the qr code and it opened in {N} Preview app automatically.
but there are some qr codes that start with nsplay: and they are not registered with {N} Preview app,
so I can't open them using external QR Code scanner.

My info is as follow:
Android: 9.0
Device: LeEco Le2
Using custom and non-official rom

**Comment by abuassar** [comment]
any updates?

**Comment by vhristov5555** [comment]
Sorry for the late response. We are using `"nativescript-barcodescanner": "3.0.3",` in the playground app. So this bug should be moved there(https://github.com/EddyVerbruggen/nativescript-barcodescanner). We are not modifying it or change it. Sorry for the inconvenience caused.
