### ISSUE TITLE
error in the code at the second step 2/9 HelloWorld.vue

### ISSUE THREAD

**Issue by 700brains** [NativeScript/playground-feedback#123]
Good Day, Am having an error with the below code on step 2/9 HelloWorld.vue
Error given is these ::
An error occurred while parsing components/HelloWorld.vue. Check for syntax errors and try again.
i just copied and paste from the tutorial section from play.nativscript.org

```
<template>
	<Page class="Page" actionBarHidden="true" backgroundSpanUnderStatusBar="true">
		<GridLayout rows="auto,auto">
			<StackLayout row="0">
				<Label class="bold" :text="city"></Label>
                <Label :text="summary"></Label>
                <Image class="weather-image" :src="image" />

                <GridLayout class="weather-box" columns="1*,1*" rows="auto">
                    <Label col="0" row="0" class="large" :text="currentTemperature"></Label>
                    <StackLayout col="1" row="0">
                        <Label class="small bold" text="details"></Label>
                        <StackLayout class="hr-light tight"></StackLayout>
                        <Label class="small" :text="humidity"></Label>
                        <Label class="small" :text="windSpeed"></Label>
                        <Label class="small" :text="visibility"></Label>
                    </StackLayout>
                </GridLayout>
            
            </StackLayout>
            
            <StackLayout row="1">
                <Label :text="day"></Label>
                <Label :text="time"></Label>
            </StackLayout>
        </GridLayout>
    </Page>
</template>
```

**Comment by darind** [comment]
@700brains, did you replace the entire contents of `HelloWorld.vue` file with this snippet? Actually you should only replace the `<template>` section and leave the `<script>` and `<style>` sections so that your final code looks like this:

```vue
<template>
    <Page class="Page" actionBarHidden="true" backgroundSpanUnderStatusBar="true">
        <GridLayout rows="auto,auto">
            <StackLayout row="0">
                <Label class="bold" :text="city"></Label>
                <Label :text="summary"></Label>
                <Image class="weather-image" :src="image" />

                <GridLayout class="weather-box" columns="1*,1*" rows="auto">
                    <Label col="0" row="0" class="large" :text="currentTemperature"></Label>
                    <StackLayout col="1" row="0">
                        <Label class="small bold" text="details"></Label>
                        <StackLayout class="hr-light tight"></StackLayout>
                        <Label class="small" :text="humidity"></Label>
                        <Label class="small" :text="windSpeed"></Label>
                        <Label class="small" :text="visibility"></Label>
                    </StackLayout>
                </GridLayout>

            </StackLayout>

            <StackLayout row="1">
                <Label :text="day"></Label>
                <Label :text="time"></Label>
            </StackLayout>
        </GridLayout>
    </Page>
</template>

<script>
    export default {
        data() {
            return {};
        }
    };
</script>

<style scoped>
    .home-panel {
        vertical-align: center;
        font-size: 20;
        margin: 15;
    }

    .description-label {
        margin-bottom: 15;
    }
</style>
```

**Comment by 700brains** [comment]
> @700brains, did you replace the entire contents of `HelloWorld.vue` file with this snippet? Actually you should only replace the `<template>` section and leave the `<script>` and `<style>` sections so that your final code looks like this:
> 
> ```
> <template>
>     <Page class="Page" actionBarHidden="true" backgroundSpanUnderStatusBar="true">
>         <GridLayout rows="auto,auto">
>             <StackLayout row="0">
>                 <Label class="bold" :text="city"></Label>
>                 <Label :text="summary"></Label>
>                 <Image class="weather-image" :src="image" />
> 
>                 <GridLayout class="weather-box" columns="1*,1*" rows="auto">
>                     <Label col="0" row="0" class="large" :text="currentTemperature"></Label>
>                     <StackLayout col="1" row="0">
>                         <Label class="small bold" text="details"></Label>
>                         <StackLayout class="hr-light tight"></StackLayout>
>                         <Label class="small" :text="humidity"></Label>
>                         <Label class="small" :text="windSpeed"></Label>
>                         <Label class="small" :text="visibility"></Label>
>                     </StackLayout>
>                 </GridLayout>
> 
>             </StackLayout>
> 
>             <StackLayout row="1">
>                 <Label :text="day"></Label>
>                 <Label :text="time"></Label>
>             </StackLayout>
>         </GridLayout>
>     </Page>
> </template>
> 
> <script>
>     export default {
>         data() {
>             return {};
>         }
>     };
> </script>
> 
> <style scoped>
>     .home-panel {
>         vertical-align: center;
>         font-size: 20;
>         margin: 15;
>     }
> 
>     .description-label {
>         margin-bottom: 15;
>     }
> </style>
> ```

Yes i did, i removed all codes. I will replace the css and JavaScript codes and try again. Will definitely let you know the outcome. Thanks

**Comment by 700brains** [comment]
@darind is working thanks to you, closing these thread.
