### ISSUE TITLE
Lost project

### ISSUE THREAD

**Issue by ptondereauSopSte** [NativeScript/playground-feedback#125]
Hey,

I just reconnect to my NativeScript account with facebook.
I'm not able to recover my project.... I changed my facebook email since the last time i connect.... Please tell me i have not lost my project and it is store somewhere....

**Comment by vhristov5555** [comment]
Тhis is a known limitation - the email is used to identify the user and his projects. Changing the email is making you a new user. The projects are not lost, they are just stored under your old email. We can update our database with your new email so that the projects re-appear in your account. For this purpose we need your old and new email.

**Comment by ptondereauSopSte** [comment]
Hi,Thank’s for your quick answer !The old email is paulbertrand567@yahoo.fr and the new one is paul.tondereau@yahoo.frThank’s a lot !Have a good day !

On Thursday, January 31, 2019, 12:51 PM, Vasil Hristov <notifications@github.com> wrote:


Тhis is a known limitation - the email is used to identify the user and his projects. Changing the email is making you a new user. The projects are not lost, they are just stored under your old email. We can update our database with your new email so that the projects re-appear in your account. For this purpose we need your old and new email.

**Comment by darind** [comment]
@ptondereauSopSte, we have updated your playground sessions, so that they point to the new email address: paul.tondereau@yahoo.fr

You should now be able to see your existing projects. Please let us know if you are still experiencing any issues with your account.

**Comment by ptondereauSopSte** [comment]
It all works ! Thank's a lot for your work, it was quick and efficient !
