### ISSUE TITLE
Dont feed data

### ISSUE THREAD

**Issue by arturn1** [NativeScript/playground-feedback#128]
https://play.nativescript.org/?template=play-vue&id=5UQuCj&v=58

My code does not work.
Why?
The currencies obtained trought from fetch method, do not feed the currencies data.

**Comment by vhristov5555** [comment]
As I could see in https://play.nativescript.org/?template=play-vue&id=5UQuCj&v=61 you were able to do it. You can find some documentation https://docs.nativescript.org/vuejs/ns-ui/AutoCompleteTextView/aync-data . This issue is not related with Playground itself so I will close it.
