### ISSUE TITLE
Fail to save added folder

### ISSUE THREAD

**Issue by ShawnPavel** [NativeScript/playground-feedback#13]
### Tell us about the problem
I have an Angular playground. I created a new component/module in a second folder within the app folder. It works great on the device and I can navigate between the two components. 

However if I save it and then reopen it from the "projects" section later, the new folder I created is gone.

### Which browser are you using?
- Chrome
- Mozilla

### Are there any errors/warnings logged in your browser console?
No.

### Which platform(s) does your issue occur on?
- iOS
- Android
- Both

### Are there any entries logged in the Device Logs tab?
Just the fact that the component is no longer there if I try to navigate to it.

### Please tell us how to recreate the issue with as much detail as possible.
Here's the playground for reference:
https://play.nativescript.org/?template=play-ng&id=9sMRXz&v=5

Note that before I open the saved version the explorer looks like this:
![screen shot 2018-02-27 at 11 38 48 am](https://user-images.githubusercontent.com/20006215/36741364-e1f8e690-1bb2-11e8-917d-5809ac22a05f.png)

And after the page2 folder is gone.

**Comment by vhristov5555** [comment]
We have reproduced the issue. We are going to adress and fix it. We will notify you when it is fixed.

**Comment by vhristov5555** [comment]
We have fixed the issue causing the problem. Also, we have fixed the version you have given us. In such way if you open your link it is going to work. Please do not hesitate to write if you have any further problems.
