### ISSUE TITLE
migrate nativescript-fresco to nativescript-image

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/playground-feedback#136]
### Did you search for the problem in [other open issues in this repo](https://github.com/NativeScript/playground-feedback/issues)?
YES

### Tell us about the problem
Plugin `nativescript-fresco` is deprecated and moved to `nativescript-image` plugin. please add support for it.

**Comment by vtrifonov** [comment]
Now we use **nativescript-image** instead of **nativescript-fresco** plugin.
