### ISSUE TITLE
Error with the demo credentials on step 12/20 of the Groceries app

### ISSUE THREAD

**Issue by ghost** [NativeScript/playground-feedback#137]
Hi ,

Congrats for your really nice and helpful Groceries app tutorial!
Maybe you can fix one little detail on the step 12/20.

At the end of the explanation, to make the preview work, the credentials should be 

email: "nativescriptrocks@progress.com"
instead of 
email: "user@nativescript.org"

**Comment by vhristov5555** [comment]
We have applied a fix addressing this issue.
