### ISSUE TITLE
Suggestion: Add nativescript-camera plugin

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/playground-feedback#14]
Since using the camera is a pretty common scenario, it would be great if the `nativescript-camera` plugin could be added to the Preview app.

**Comment by darind** [comment]
@rdlauer thanks for the suggestion. We have planned to include this plugin along with some others (`nativescript-fresco`, `nativescript-intl`, `nativescript-iqkeyboardmanager`, `nativescript-social-share` and the latest split pro UI packages) in the next version of the Preview app.

**Comment by rdlauer** [comment]
Awesome. @tjvantoll for visibility into this as well.

**Comment by darind** [comment]
A new version of the Preview app containing those plugins is now available in the app stores.
