### ISSUE TITLE
[FeatureRequest] - View package.json

### ISSUE THREAD

**Issue by shiv19** [NativeScript/playground-feedback#140]
Please allow us to view the package.json in READONLY mode on the playground, so that we don't have to download the project, just to take a look at the versions being used.

**Comment by vtrifonov** [comment]
@shiv19 you can see the versions in the devices tab once you connect your device:
![image](https://user-images.githubusercontent.com/2012477/58404784-9d942380-806e-11e9-8f11-cc1ebbb034cf.png)
You can check the following [post](https://www.nativescript.org/blog/dependency-versions-in-nativescript-playground) for more details about the versions in playground.

**Comment by shiv19** [comment]
Thanks! 😃
