### ISSUE TITLE
New angular project :  ERROR TypeError: Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/playground-feedback#15]
When creating a new angular project ,  I get error : 

![image](https://user-images.githubusercontent.com/2842123/36974467-7a02c0e8-207f-11e8-81e8-c5a541e6cde2.png)

**Comment by darind** [comment]
@RoyiNamir, could this logged message be a leftover from a previous session? Are you still seeing it after clearing the device logs, closing the Preview app and re-scanning the QR code of a newly created angular project?

**Comment by RoyiNamir** [comment]
Indeed , it was leftovers from previous session. Forgot to close. thank.
