### ISSUE TITLE
SASS folders can't be imported

### ISSUE THREAD

**Issue by bundyo** [NativeScript/playground-feedback#151]
### Did you search for the problem in [other open issues in this repo](https://github.com/NativeScript/playground-feedback/issues)?
Yes. There is a similar issue #18, but it was reported fixed. On second test - no - the old theme imports directly the index files, so probably this was always broken.

### Tell us about the problem
If there is a SCSS file in a folder and it imports another folder (with an _index.scss file in it), the import fails with an error that a file with the folder name is not found.

This will probably prevent users from using SASS based frameworks from npm (including a specific version of NativeScript Theme).

As an additional issue - after the import fails - clicking on any file in the explorer will hang the Playground with a never-ending loader.

### Did you try it outside of {N} Playground?
- Yes - but the behavior is different - it works :)

### Are there any errors/warnings logged in your browser console?
```
Error: File to import not found or unreadable: ./scss/core.
Parent style sheet: /sass/nativescript-theme-core@2.0.4/core.compat.scss
on line 10 of sass/nativescript-theme-core@2.0.4/core.compat.scss
>> @import './scss/core';
```

### Please tell us how to recreate the issue with as much detail as possible.
Open [this URL](https://play.nativescript.org/?template=play-tsc&id=AosTnJ), un-comment the row in test.scss and try to save.

**Comment by CoooWeee** [comment]
I got the same issue when I use:
`@import "~nativescript-theme-core/core";`

**Are there any errors/warnings logged in your browser console?**

```
ERROR in ./app.scss
Module build failed (from ../node_modules/sass-loader/lib/loader.js):

@import './scss/core';
^
      File to import not found or unreadable: ./scss/core.
      in ˜node_modules/nativescript-theme-core/core.scss
```

**Comment by vhristov5555** [comment]
We have deploy a fix for enabling import SASS folders
