### ISSUE TITLE
Introduce the ability to enter the QR Codes manually (Not scanned using Camera)

### ISSUE THREAD

**Issue by muhassaf** [NativeScript/playground-feedback#159]
I am using nativescript to develop an app for android device without a camera (an android restaurant self service ordering screen) 

is there a way to copy the QR code without a camera,

Thanks.

**Comment by vtrifonov** [comment]
Hi @muhassaf, we have a BETA functionality which you can try to use for your case. You can do the following: 
1. Open [https://play.nativescript.org?enablePin=true](https://play.nativescript.org?enablePin=true) (you need to add enablePin=true query string parameter)

2. Then when you open the QR screen you should see the following at the bottom:
![image](https://user-images.githubusercontent.com/2012477/64944536-3d242e80-d877-11e9-9e1a-ea731b5dc410.png)
then press the Generate button

3. On your mobile device open the same URL in the browser - [https://play.nativescript.org?enablePin=true](https://play.nativescript.org?enablePin=true) (make sure you add enablePin=true) and you should see something like this:
![image](https://user-images.githubusercontent.com/2012477/64944731-ac9a1e00-d877-11e9-8b33-b86f3fb61c09.png)

4. Enter the PIN from the website and press **Load** and you should see this:
![image](https://user-images.githubusercontent.com/2012477/64944872-013d9900-d878-11e9-839b-7bb0fddfb0e7.png)

5. Pressing the **Open NativeScript Preview app** should open and sync the application on your device.
 
I hope this helps.

**Comment by muhassaf** [comment]
Worked perfectly :)
