### ISSUE TITLE
Suggestion: Add nativescript-background-http plugin

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/playground-feedback#17]
since uploading file is basic requirement of any app now a day, it will be usefull if plugin is available.

**Comment by vhristov5555** [comment]
Thank you for the feedback.
We are going to add this request to our backlog.
In the next release of the preview app we are going to include the plugin.

**Comment by darind** [comment]
@bhavincb, a new version of the Preview app is available in the Google Play Store containing the `nativescript-background-http` plugin.
