### ISSUE TITLE
Saving file takes too long!

### ISSUE THREAD

**Issue by dotnetdreamer** [NativeScript/playground-feedback#170]
## Please, provide the details below:
I am trying save a file but its taking too long and at the end not able to save it. 

### Did you search for the problem in [other open issues in this repo](https://github.com/NativeScript/playground-feedback/issues)?
Yes

### Did you try it outside of {N} Playground?
- No

### Which browser are you using?
- Chrome

### Are there any errors/warnings logged in your browser console?
No

### Which platform(s) does your issue occur on?
- iOS
- Android
- Both

### Are there any entries logged in the Device Logs tab?
No

### Please tell us how to recreate the issue with as much detail as possible.
Use the following link, go to app.component.ts and import the service from filepicker.service.ts and then try to save. Sometime isn't not even loading hte project:

[https://play.nativescript.org/?template=play-ng&id=RvWEPu&v=4](https://play.nativescript.org/?template=play-ng&id=RvWEPu&v=4
)

**Comment by vtrifonov** [comment]
Seems that the size of the project is quite big which causes the API to time out. I see that you've added the tns-platform-declarations package to your project, which is not recommended as it is quite big for the browser.
