### ISSUE TITLE
Unable to use vue-router

### ISSUE THREAD

**Issue by paidTrainee27** [NativeScript/playground-feedback#20]
Im getting follwing error when i tried to use vue-router plugin that I downloaded using npm package feature available on playground.

`Error: com.tns.NativeScriptException: Failed to find module: "vue-router", relative to: app/tns_modules/`

Below is the link to apllication:
[https://play.nativescript.org/?template=play-vue&id=T25SIi&v=2](url)

**Comment by vhristov5555** [comment]
Hi, 
Thanks for you feedback.
You are trying to import vue-router as a global module. Instead when adding NPM package through playground you should import it relatively. In your case "const VueRouter = require('./vue-router');". 
I have updated the example:
https://play.nativescript.org/?template=play-vue&id=T25SIi&v=3

**Comment by paidTrainee27** [comment]
Thanks for you quick reply...

**Comment by vhristov5555** [comment]
I am glad I could help you. Have a nice day.
