### ISSUE TITLE
Unable to Delete/Rename Folder/File

### ISSUE THREAD

**Issue by paidTrainee27** [NativeScript/playground-feedback#22]
Hi,
Currently in my newly created project I want to change the default generated folder(home) and file names by clicking the three dots on right of file/folder , but I'm unable to . It use to happen earlier i guess.
Now i'm force to delete old and create new folder/file.
thanks.

**Comment by vhristov5555** [comment]
Hi,
You can rename files by clicking on burger icon (the three dots). When you click on the burger icon for a file (e.g. home.component.html) you will see the option for renaming a file:
![image](https://user-images.githubusercontent.com/7846198/38013577-4d33ebea-326e-11e8-88f3-d42c27ee73e8.png)
Unfortunately renaming a folder is not supported in the moment. As a workaround, you could create new folder and drag and drop the files from the current folder to the newly created.

**Comment by paidTrainee27** [comment]
But in my project unable to change even the file name's ..
check : myproject
<https://play.nativescript.org/?template=play-ng&id=PiaOQw&v=2>

**Comment by vhristov5555** [comment]
Hi,

I was able to rename a file successfully in Chrome:

![image](https://user-images.githubusercontent.com/7846198/38014469-8855cee8-3271-11e8-9438-58109d589285.png)

- Which browser and version are you using?
- Do you see the Rename option?
- Do you have some errors in the browser console?

**Comment by paidTrainee27** [comment]
Hi,
There was issue with my chrome browser, I did audit for the website and now
it is showing the option to rename the files.
thanks

**Comment by vhristov5555** [comment]
I am glad that you have resolved the issue.
If you have further question please write to us.
I will close this issue.
