### ISSUE TITLE
Bug: Platform specific files don't work as intended on playground.

### ISSUE THREAD

**Issue by shiv19** [NativeScript/playground-feedback#24]
Steps to reproduce:

Create a new playground app (any stack)

duplicate any view file, rename one to `<name>.android.xml` (or html),
and the other to `<name>.ios.xml` (or html)

App crashes because it can't find `<name>.xml` (or html)

however, if I keep the `<name>.xml` (or html) file around. Then the platform specific files work
as expected.

**Comment by shiv19** [comment]
Another workaround, it to reconnect the device to playground after making platform specific files.

In this approach, platform-specific files work as intended.

and you won't have to keep `<name>.xml` in the project directory anymore.

**Comment by vhristov5555** [comment]
We have fixed the issue and deployed it to Live.
If you have further problems or comments please write to us.

**Comment by shiv19** [comment]
Awesome! Thank you :D

**Comment by vhristov5555** [comment]
You are welcome :)
