### ISSUE TITLE
Small Typo in the Tutorial

### ISSUE THREAD

**Issue by MyLightIsOn** [NativeScript/playground-feedback#28]
![screen shot 2018-05-01 at 8 50 15 am](https://user-images.githubusercontent.com/2665198/39473462-fd538fd0-4d1c-11e8-86a0-39dc40ce9cfa.png)

I believe this is supposed to be "do not work in NativeScript apps".

**Comment by vhristov5555** [comment]
Thanks for the feedback.
We have fixed the issue.
