### ISSUE TITLE
Logging objects only prints a `{` char in the device logs.

### ISSUE THREAD

**Issue by Mike96Angelo** [NativeScript/playground-feedback#29]
### Tell us about the problem
Logging objects doesn't show anything other than a `{` character.  This makes debugging objects hard.

### Did you try it outside of {N} Playground?
- No

### Which browser are you using?
- Safari

### Are there any errors/warnings logged in your browser console?
- No

### Which platform(s) does your issue occur on?
- iOS
- Both (maybe, I only have an iOS device)

### Please provide the following information shown in devices tab in the playground:
| Model | OS version | Preview app version | Runtime version |
|:------:|:-----------:|:--------------------:|:----------------:|
| iPhone 7  | iOS 11.3.1 | 1.11.0 | 4.0.1 |

### Please tell us how to recreate the issue with as much detail as possible.

example:
```
console.log({ test: 'test' })
```

If you look in the **Device Logs** you will see:
```
[<divice-name>]:   {
```

The rest of the object is missing.

**Comment by vhristov5555** [comment]
Hi,
Sorry for the inconvenience caused.

This is a bug on our side.
We are going to add it to our backlog.

Thank you for the feedback.

**Comment by darind** [comment]
This issue should be resolved with the latest version of the Preview app. Please do not hesitate to re-open this issue if some problems persist.
