### ISSUE TITLE
Even import module it shows error xmldom module not found !

### ISSUE THREAD

**Issue by ann1111** [NativeScript/playground-feedback#38]
Even import module it shows error xmldom  module not found

![image](https://user-images.githubusercontent.com/12736476/40727117-d1916f90-6444-11e8-8329-6e724fa3fe64.png)
https://play.nativescript.org/?template=play-ng&id=yleJE9&v=4

as per this 
import { Component, OnInit } from "@angular/core";
import { DOMParser as dom } from "xmldom";
import * as Xpath from "xpath";
import {request} from "http";
import { Item } from "./item";
import { ItemService } from "./item.service";

@Component({
   selector: "ns-items",
   moduleId: module.id,
   templateUrl: "./items.component.html",
})

https://www.nativescript.org/blog/handle-xml-response-from-soap-service-in-nativescript

![image](https://user-images.githubusercontent.com/12736476/40727093-c2a46c44-6444-11e8-84af-735311d61fc3.png)

**Comment by ann1111** [comment]
Still not works with ASP.Net soap xml

https://play.nativescript.org/?template=play-ng&id=KNJ6SQ&v=5

**Comment by ann1111** [comment]
Ok rojer 

https://play.nativescript.org/?hideQR=true&template=play-ng&id=kJAQVe&file=home%2Fhome.component.ts&v=17

Actually I too following this its angullar section they have metion like that so bit confuse https://www.nativescript.org/blog/handle-xml-response-from-soap-service-in-nativescript


anyways

if you can help me to resolve this last issue 

[Panasonic Eluga A2]: ERROR Error: Uncaught (in promise): SyntaxError: Unexpected token < in JSON at position 0

![image](https://user-images.githubusercontent.com/12736476/40730402-2a45d084-644c-11e8-945a-4af8e0ba3a7f.png)

code reference was https://www.nativescript.org/blog/handle-xml-response-from-soap-service-in-nativescript its angular section it gives error like this have do setting to resolve it accordingly but unable to get response from soap xml can you check once and let me know if you can ,Thanks in advance its regading dom as well

**Comment by ann1111** [comment]
HI darind

**Comment by darind** [comment]
@ann1111, checkout the following example: https://play.nativescript.org/?template=play-ng&id=VLL7lV&file=home%2Fhome.component.ts

**Comment by ann1111** [comment]
Ok
