### ISSUE TITLE
While Preview on mobile it shows Panasonic Eluga A2]: ERROR Error: Uncaught (in promise): Error: com.tns.NativeScriptException: Failed to find module: "xml-js", relative to: app/tns_modules/

### ISSUE THREAD

**Issue by ann1111** [NativeScript/playground-feedback#39]
Module not load in Andoid device error shows 

import * as xml2json from "../xml-js";

![image](https://user-images.githubusercontent.com/12736476/40721121-39515b4a-6436-11e8-9616-7cbb71dcfaf8.png)

**Comment by jfvilasAbanca** [comment]
you must add the 'xml-js' module as explained here: https://www.tjvantoll.com/2018/03/02/playground-plugins/

**Comment by ann1111** [comment]
Hey kindly see the screenshot carefully I have already added NPM package and import as well but while preview in mobile app android it gives error

**Comment by darind** [comment]
You seem to have incorrectly referenced the `xml-js` module on line 9:

```
var convert = require('xml-js');
```

**Comment by ann1111** [comment]
Yeah I do the same i light but might still some issue wait 1 sec
![image](https://user-images.githubusercontent.com/12736476/40729231-904cf5b8-6449-11e8-8c3d-58f5cf21e401.png)

**Comment by ann1111** [comment]
[Panasonic Eluga A2]: com.tns.Module.resolvePath(Module.java:55)
[Panasonic Eluga A2]: ERROR Error: Uncaught (in promise): Error: com.tns.NativeScriptException: Failed to find module: "sax", relative to: app/tns_modules/
[Panasonic Eluga A2]:

**Comment by ann1111** [comment]
https://play.nativescript.org/?template=play-ng&id=yleJE9&v=6

**Comment by ann1111** [comment]
Can you anyhow manage to get this soap response we that's the big deal

import { Component, OnInit } from "@angular/core";
import { request } from "tns-core-modules/http";
//import { DOMParser as dom } from "../xmldom"; error here*****
import * as Xpath from "../xpath";
const dom = require("../xmldom").DOMParser;
//import * as XmlObjects from "../nativescript-xmlobjects";
import * as xml2json from "../xml-js";

//import "rxjs/Rx";
require("../sax"); 
var convert = require('../xml-js');

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html",
    styleUrls: ['./home.component.css']
})


export class HomeComponent implements OnInit {

    constructor() {
    }

    ngOnInit(): void {

        request({
            url: "http://mobileapi2.beehivesoftware.in/BeehiveMobileService.svc",
            method: "POST",
            headers: { "Content-Type": "text/xml" },
            content:
                "<?xml version='1.0' encoding='UTF-8'?>" +
                "<soapenv:Envelope xmlns:ns2='http://beehivehronline.com/v1' xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' xmlns:tem='http://tempuri.org/'>" +
                "<soapenv:Header>" +
                "<ns2:APICode>c2Fhc2hybXM=</ns2:APICode>" +
                "<ns2:APIKey>63ff0f6c-f2ba-42a5-a865-11140c92c27b-b26034be-0322-4cf8-a8bf-ebbfac2d6def</ns2:APIKey>" +
                "</soapenv:Header>" +
                "<soapenv:Body>" +
                "<tem:ValidateLogin>" +
                "<tem:username>1001</tem:username>" +
                "<tem:password>1</tem:password>" +
                "</tem:ValidateLogin>" +
                "</soapenv:Body>" +
                "</soapenv:Envelope>"
        })
            .then(function (response) {

                //  console.log(response.content.toJSON());
                console.log("i m  in response");


            }, function (e) {
                console.log("Error: " + e);
            });

    }
}

**Comment by ann1111** [comment]
Nativescript is great just in .net have issue while using soap request and collect its response I hope you understand kindly have a look and let me know rather can get soap response in it though valid library or not or suggest me

**Comment by darind** [comment]
@jfvilasAbanca, it seems that the `xml-js` package references the `sax` module globally inside `lib/xml2js.js`. Installing the `sax` package and changing the reference should resolve the issue. Please check if the following session works: https://play.nativescript.org/?hideQR=true&template=play-js&id=wmX0AJ&file=home%2Fhome-view-model.js

**Comment by jfvilasAbanca** [comment]
Now it works. I've just modified the reference to '../../sax' in my project and it now works. thanks!

**Comment by darind** [comment]
@ann1111, please check the following session which illustrates how you can invoke the SOAP service: https://play.nativescript.org/?template=play-ng&id=VLL7lV
