### ISSUE TITLE
Downloaded project bundling.

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/playground-feedback#41]
when using `--bundle` with downloaded project from playground gives several error.

```
ERROR in ./main.aot.ts
Module build failed: Error: E:\nativescript\projects\geodirectory-work\app\main.
aot.ts is missing from the TypeScript compilation. Please make sure it is in you
r tsconfig via the 'files' or 'include' property.
    at NativeScriptAngularCompilerPlugin.getCompiledFile (E:\nativescript\projec
ts\geodirectory-work\node_modules\@ngtools\webpack\src\angular_compiler_plugin.j
s:663:23)
    at NativeScriptAngularCompilerPlugin.getCompiledFile (E:\nativescript\projec
ts\geodirectory-work\node_modules\nativescript-dev-webpack\plugins\NativeScriptA
ngularCompilerPlugin.ts:63:26)
    at plugin.done.then (E:\nativescript\projects\geodirectory-work\node_modules
\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>

ERROR in ./app.css
Module not found: Error: Can't resolve './nativescript-theme-core/css/core.light
.css' in 'E:\nativescript\projects\geodirectory-work\app'
 @ ./app.css 3:10-111
 @ . nonrecursive ^\.\/app\.(css|scss|less|sass)$
 @ ./vendor.ts
Webpack compilation complete.
Executing webpack failed with exit code 2.
```

it will make sense to remove these error when user clicks download button.

**Comment by vhristov5555** [comment]
First sorry for the inconvenience caused.
This is an issue with our template. We are going to update it.
If you want to be able to build your project please edit your css file. You need to replace this line of  code:
```
@import 'nativescript-theme-core/css/core.light.css';
```
with this line of code:
```
@import '~nativescript-theme-core/css/core.light.css';
```

Thanks for the feedback.

**Comment by bhavincb** [comment]
also remove `**/main.aot.ts` from tsconfig.json `exclude` section.

**Comment by vhristov5555** [comment]
We are going to review the whole template and update it. 
Thanks for the feedback.

**Comment by vhristov5555** [comment]
Could please add more info about "remove **/main.aot.ts from tsconfig.json exclude section".
What do you want to achieve exactly?
What should be changed ?

**Comment by bhavincb** [comment]
i don't remember completely but it was giving some errors but making bellow changes  it was solved.

**tsconfig.json**
```
...
,
    "exclude": [
        "node_modules",
        "platforms",
        "typings",
        "**/*.aot.ts",
        "additional-models"
    ]
...
```
 i had to remove ` "**/*.aot.ts"` from above json to make it completely error free and run successfully

**Comment by vhristov5555** [comment]
We have tried it with and without --bundle and it is working on our side. 
Could you please give us some more information what was the problem so we could address the issue correctly.

**Comment by vhristov5555** [comment]
We have fixed and deployed the problem with :
```
@import '~nativescript-theme-core/css/core.light.css';
```
You can check if you have further problems.

**Comment by bhavincb** [comment]
i will check it and get back to you then
