### ISSUE TITLE
Feature: Nativescript offical demo or example direct import.

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/playground-feedback#47]
if there is a way from which we can directly import nativescript offical demo or sample to the Playground then it will be great feature to have it.

**Comment by darind** [comment]
@bhavincb, unfortunately the playground does not support uploading existing projects because it was designed for quickly prototyping and trying out {N} and not as a full blown development environment.

https://github.com/NativeScript/playground-feedback/issues/7

**Comment by bhavincb** [comment]
but if only support to official nativescript example can be provided then still it will be great to have it.
