### ISSUE TITLE
Object Based Json Array using Angular not able to get value from it as per angular function in playground

### ISSUE THREAD

**Issue by ann1111** [NativeScript/playground-feedback#50]
Hi 

Object Based Json Array using Angular not able to get value from it as per angular function in playground

Url : https://play.nativescript.org/?template=play-ng&id=7rP5SC&v=4
home.component.ts
though this :  
 ```
var result2 = xmljs.xml2json(response.content); console.log(result2);
 ```
we got following json array now I am trying get value a:IsError  from this array I follow angular js stype logic but seems its not working in nativescript while run in playground 
 ```
{"elements":[{"type":"element","name":"s:Envelope","attributes":{"xmlns:s":"http://schemas.xmlsoap.org/soap/envelope/"},"elements":[{"type":"element","name":"s:Body","elements":[{"type":"element","name":"ValidateLoginResponse","attributes":{"xmlns":"http://tempuri.org/"},"elements":[{"type":"element","name":"ValidateLoginResult","attributes":{"xmlns:a":"http://schemas.datacontract.org/2004/07/BeehiveHrms.MobileServices","xmlns:i":"http://www.w3.org/2001/XMLSchema-instance"},"elements":[{"type":"element","name":"a:ErrorMsg","elements":[{"type":"text","text":"Please enter valid username and password."}]},{"type":"element","name":"a:IsError","elements":[{"type":"text","text":"true"}]},{"type":"element","name":"a:IsActive","elements":[{"type":"text","text":"false"}]},{"type":"element","name":"a:IsAttendance","elements":[{"type":"text","text":"false"}]},{"type":"element","name":"a:IsCalendar","elements":[{"type":"text","text":"false"}]},{"type":"element","name":"a:IsCirculars","elements":[{"type":"text","text":"fa...
 ```
I want value from a:IsError from this array 

Can you get value in this editor so I can work further, thanks

In Angular its working I can get a:IsError node value but in nativescript angular js playground still not needs your help once  : 
 ```JavaScript
var app = angular.module('myApp', []);
app.controller('myCtrl', function($scope) {
  $scope.JSON = {
    "elements": [{
      "type": "element",
      "name": "s:Envelope",
      "attributes": {
        "xmlns:s": "http://schemas.xmlsoap.org/soap/envelope/"
      },
      "elements": [{
        "type": "element",
        "name": "s:Body",
        "elements": [{
          "type": "element",
          "name": "ValidateLoginResponse",
          "attributes": {
            "xmlns": "http://tempuri.org/"
          },
          "elements": [{
            "type": "element",
            "name": "ValidateLoginResult",
            "attributes": {
              "xmlns:a": "http://schemas.datacontract.org/2004/07/BeehiveHrms.MobileServices",
              "xmlns:i": "http://www.w3.org/2001/XMLSchema-instance"
            },
            "elements": [{
                "type": "element",
                "name": "a:ErrorMsg",
                "attributes": [{
                  "type": "text",
                  "text": "Please enter valid username and password."
                }]
              },
              {
                "type": "element",
                "name": "a:IsError",
                "elements": [{
                  "type": "text",
                  "text": "true"
                }]
              },
              {
                "type": "element",
                "name": "a:IsActive",
                "elements": [{
                  "type": "text",
                  "text": "false"
                }]
              }
            ]
          }]
        }]
      }]
    }]
  }

  // recursive function
  function findNode(elem, currentNode) {
    var i,
      currentChild,
      result;

    if (elem == currentNode["name"]) { // can be a dynamic key
      return currentNode;
    } else {
      if (currentNode["elements"]) { // can be a dynamic key
        for (i = 0; i < currentNode["elements"].length; i++) {
          currentChild = currentNode["elements"][i];

          result = findNode(elem, currentChild);

          if (result !== false) {
            return result; // found
          }
        }
      }
      return false; // not found
    }
  }


  $scope.find = function() {
    var res;
    res = findNode($scope.search, $scope.JSON);
    if (res) {
      $scope.found = angular.copy(res.elements[0]);
    } else {
      $scope.found = null;
    }
  }
  $scope.search = "a:IsError";
  $scope.find();
});
 ```

**Comment by ann1111** [comment]
Basically 

I want to read xml/json SOAP response value but it not works it can work in angular js and java android but not works in nativescript angular js can you check once for few sec home.component.ts is the file name

main xml soal response is 

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <ValidateLoginResponse xmlns="http://tempuri.org/">
         <ValidateLoginResult xmlns:a="http://schemas.datacontract.org/2004/07/BeehiveHrms.MobileServices" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
            <a:ErrorMsg>Please enter valid username and password.</a:ErrorMsg>
            <a:IsError>true</a:IsError>
            <a:IsActive>false</a:IsActive>
            <a:IsAttendance>false</a:IsAttendance>
            <a:IsCalendar>false</a:IsCalendar>
            <a:IsCirculars>false</a:IsCirculars>
            <a:IsDashboard>false</a:IsDashboard>
            <a:IsDirectory>false</a:IsDirectory>
            <a:IsEmployeeDesk>false</a:IsEmployeeDesk>
            <a:IsEmployeeDeskAttendance>false</a:IsEmployeeDeskAttendance>
            <a:IsEmployeeDeskExpense>false</a:IsEmployeeDeskExpense>
            <a:IsEmployeeDeskLeave>false</a:IsEmployeeDeskLeave>
            <a:IsEmployeeDeskOutdoor>false</a:IsEmployeeDeskOutdoor>
            <a:IsEmployeeDeskTravel>false</a:IsEmployeeDeskTravel>
            <a:IsHoliday>false</a:IsHoliday>
            <a:IsLeave>false</a:IsLeave>
            <a:IsManager>false</a:IsManager>
            <a:IsManagerDesk>false</a:IsManagerDesk>
            <a:IsManagerDeskAttendance>false</a:IsManagerDeskAttendance>
            <a:IsManagerDeskExpense>false</a:IsManagerDeskExpense>
            <a:IsManagerDeskLeave>false</a:IsManagerDeskLeave>
            <a:IsManagerDeskOutdoor>false</a:IsManagerDeskOutdoor>
            <a:IsManagerDeskTravel>false</a:IsManagerDeskTravel>
            <a:IsOutdoor>false</a:IsOutdoor>
            <a:IsPolicies>false</a:IsPolicies>
            <a:IsTimeInOut>false</a:IsTimeInOut>
            <a:IsValid>false</a:IsValid>
            <a:UserID>0</a:UserID>
         </ValidateLoginResult>
      </ValidateLoginResponse>
   </s:Body>
</s:Envelope>

needs to read values from tags

**Comment by vhristov5555** [comment]
Hi,
Sorry for the inconvenience cause.

Could please try this problem outside of The Playground?
Could you download the project and run it through Nativescript CLI(https://docs.nativescript.org/angular/start/hello-world/ng-chapter-1) or Nativescript Sidekick(https://www.nativescript.org/nativescript-sidekick).

**Comment by ann1111** [comment]
Ok Bro also I done 

here is the code

import { Component } from "@angular/core";
import { request } from "tns-core-modules/http";
import * as Xpath from "../xpath";
import * as xml2json from "../xml-js";
const dom = require("../xmldom").DOMParser;
const convert = require('../xml-js');
var xmljs = require('../xml-js');
import { parseString } from "../nativescript-xml2js";

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html",
    styleUrls: ['./home.component.css']
})


export class HomeComponent {
    constructor() {
    }

    callSOAPService(): void {
        request({
            url: "http://mobileapi2.beehivesoftware.in/BeehiveMobileService.svc",
            method: "POST",
            headers: {
                "Content-Type": "text/xml; charset=utf-8",
                "SOAPAction": "http://tempuri.org/IBeehiveMobileService/ValidateLogin"
            },
            content: `<?xml version="1.0" encoding="UTF-8"?>
            <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
                <s:Header>
                    <APIKey xmlns="http://beehivehronline.com/v1">63ff0f6c-f2ba-42a5-a865-11140c92c27b-b26034be-0322-4cf8-a8bf-ebbfac2d6def</APIKey>
                    <APICode xmlns="http://beehivehronline.com/v1">c2Fhc2hybXM=</APICode>
                </s:Header>
                <s:Body>
                    <ValidateLogin xmlns="http://tempuri.org/">
                        <username>fgg</username>
                        <password>gf</password>
                    </ValidateLogin>
                </s:Body>
            </s:Envelope>`
                    })
            .then(function (response) {
                console.log(response.content);
               

                parseString(response.content, (error, result2) => {
                    if (error) {
                        console.log("Parse error:", error);
                        return;
                    }

                   // console.log(result2["s:Envelope"]["s:Body"][0]['ValidateLoginResponse'][0]['ValidateLoginResult'][0]['a:IsError']);
                    var iserror = result2["s:Envelope"]["s:Body"][0]['ValidateLoginResponse'][0]['ValidateLoginResult'][0]['a:IsError'];

                    //console.log(iserror);
                    if (iserror == 'true') {

                        console.log('ok');
                    }
                    else { 
                        console.log('do agian');
                    }

                });
               // var result2 = xmljs.xml2json(response.content);
              //  console.log(result2);
              //  console.log(result2.elements[0].elements[0].elements[0].elements[0].elements[1].elements[0].text);
              //  console.log(JSON.parse(result2));
              

                //  console.dir(JSON.stringify(result2));
            }, function (e) {
                console.log("Error: " + e);
            });
    }
}

**Comment by vhristov5555** [comment]
I am pleased to hear that you have managed to resolve it.

Have a nice day.

**Comment by ann1111** [comment]
Thanks

**Comment by ann1111** [comment]
import { parseString } from "../nativescript-xml2js"; works fine for soap xml
