### ISSUE TITLE
After save The Groceries tuto always Jumps back to Section 3 (windows, Javascript)

### ISSUE THREAD

**Issue by nabhan0705** [NativeScript/playground-feedback#55]
It's about a simple bug.  I am doing the Groceries Tutorial.  You see, at the right bottom, there is the Previous Button Then Section Number like 3/20, Next there is a 'completed' button. I think that would serve as the NEXT button. But I cannot use that button. Whenever I bring the mouse over ir the tooltip text completely covers it. The only remaining option is using the section number in the center. But every time I SAVE the project it REVERTS to section 3.  That is, Say I have done section 9 and Save, the Tutorial jumps back to section 3. So the Bottom Number ALWAYS show 3/20, and the tutorial Content is of Section 3, after each SAVE.  Otherwise, everything fine. The new look and features are good

**Comment by vhristov5555** [comment]
Hi,

Sorry for the inconvenience caused.

The Complete step button is enabled only if you are following the flow from step 1, step 2, step 3 ... till the last step.
If you skip a step by navigating from step 3 to step 5 by the dropdown(e.g. section number 3/20 to 5/20) the complete button will be disabled and a tooltip "To complete a step you need to complete all previous steps first" will be shown.
If you save the tutorial you will be navigated to the first step in the current lesson or to next step on which you have click Complete step. 
For example if you click Complete step button for step 1 and step 2, navigate to step 5 and click Save you will be navigated to step 3. 

Hope this helps.

**Comment by nabhan0705** [comment]
Hi, Thank you for the reply.

I am following the Tuto in the Proper order itself

'Complete Button' is getting entirely covered by the Tooltip Text.

I would like to suggest, You could take the Entire Navigation Palette to
the top, rather than the bottom

Regards

**Comment by nabhan0705** [comment]
Thank You. For 2 months,off and on, I was trying, No luck. Yesterday it
worked fine. No any hitches. I have completed the tuto in 30 minutes flat.
(Anyway it is Windows 7, 32 bits, Javascript, Chrome Latest. Tooltip was as
I remember. 'To complete you have to complete all previous...", something
like that." Yesterday it didnt appear.)

**Comment by vhristov5555** [comment]
I am happy that you have managed to finish it.

Hope you were satisfied with the experience and the knowledge gained.
Now you can try:
 - NativeScript Sidekick(https://www.nativescript.org/nativescript-sidekick)
 - NativeScript CLI(https://docs.nativescript.org/angular/start/introduction)

I will close this issue.

If you have further problems feel free to write to us.

Best Regards, 
Vasil Hristov

**Comment by nabhan0705** [comment]
Hi Hristov, I am using Windows 7 Ultimate 32 bit. Seems like Sidekick does
not instal on 32 bit machines.
Any alternatives?

Regards

Padmanabhan

**Comment by ggarabedian** [comment]
Hello @nabhan0705,

Unfortunately, the NativeScript Sidekick client supports only 64-bit OSs. The only alternative is already suggested by Vasil - the [NativeScript CLI](https://docs.nativescript.org/angular/start/introduction) can be installed and used on all major operating systems (32 and 64 bit).

Please, let us know if you have any additional questions about the NativeScript CLI or something else.

**Comment by nabhan0705** [comment]
Oh, Thank You for the tiip. I had thought The CLI thing was to be used in
conjunction with SideKick. I will try now.

Regards

**Comment by nabhan0705** [comment]
Hi,

I tried The Groceries Tuto I had completed online and saved on lappy, With
CLI and Also with Visual Studio Code.

The build fails  (plz see the Attachment)

Regards
