### ISSUE TITLE
Cannot find module 'utils/utils'

### ISSUE THREAD

**Issue by wanpeng2008** [NativeScript/playground-feedback#59]
new angular2+nativescript project
import utils/utils to  home.component.ts
````
import * as utils from "utils/utils";
````
Then error thrown
````
home/home.component.ts (2, 24): Cannot find module 'utils/utils'.
````

**Comment by vhristov5555** [comment]
Hi,

Sorry for the inconvenience cause.
This is an issue on our side. We are going to fix it.

As a workaround you can use:
```import * as utils from "tns-core-modules/utils/utils";```

Best Regards,
Vasil Hristov

**Comment by vhristov5555** [comment]
We have deployed a fix to the problem.
