### ISSUE TITLE
Step 17 in Groceries tutorial

### ISSUE THREAD

**Issue by mcasto** [NativeScript/playground-feedback#62]
### Did you search for the problem in [other open issues in this repo](https://github.com/NativeScript/playground-feedback/issues)?
I did. I saw nothing that seemed related.

### Tell us about the problem
The "add" function does nothing, and I get no feedback in the console.

### Did you try it outside of {N} Playground?
- Yes - it has the same behavior as in the playground

### Which browser are you using?
- Safari

### Are there any errors/warnings logged in your browser console?
[Warning] ArrayBuffer is deprecated in XMLHttpRequest.send(). Use ArrayBufferView instead. (polyfills.83eae7a6f974379c3a63.js, line 1)

### Which platform(s) does your issue occur on?
- iOS
I'm unable to test on Android simulator.

### Are there any entries logged in the Device Logs tab?
No.

### Please provide the following information shown in devices tab in the playground:
- iPhone 7
- iOS 11.4.1
- 1.13.0
- 4.1.0

### Please tell us how to recreate the issue with as much detail as possible.
You recommend getting the problem working in Playground, but that *is* my problem. It doesn't work in Playground. I *think* this is the link to the Playground project: 
https://play.nativescript.org/?template=groceries-js&id=OWyAT9&v=12

I'm going through the Groceries tutorial and, at Step 17, the "Add" button does nothing, and I get no feedback in the Device Logs or Errors console when I click the "+".

**Comment by vhristov5555** [comment]
Hi,

I have found the problem causing this behaviour.
In step 16 - Action 2 :
```
a. Start by changing app/views/list/list.js to use the GroceryListViewModel. First, require() the GroceryListViewModel so you can use it:

var GroceryListViewModel = require("../shared/view-models/grocery-list-view-model");
```
You need to require() the GroceryListViewModel so you can use it.
You can find the working version : https://play.nativescript.org/?template=groceries-js&id=OWyAT9&v=13

Hope this helps.

Best Regards,
Vasil Hristov
