### ISSUE TITLE
What version of nativescript-vue is used in playground?

### ISSUE THREAD

**Issue by odai-alali** [NativeScript/playground-feedback#63]
Is there a way to choose a specific version?

**Comment by vhristov5555** [comment]
Package versions are shown in device tab for selected devices:
![image](https://user-images.githubusercontent.com/7846198/43645793-a900f396-973b-11e8-8d9f-bb66151ecddf.png)
The current nativescript-vue version is 1.3.1.
In the moment there is no option to select different versions.
We are updating the packages version regularly when we plan a new release.

Hope this helps.

Best Regards,
Vasil Hristov

**Comment by odai-alali** [comment]
Thanks @vhristov5555
