### ISSUE TITLE
DataForm Picker from VueJS Examples Needed

### ISSUE THREAD

**Issue by fwarren** [NativeScript/playground-feedback#64]
## Please, provide the details below:
When using the Playground with Vue, it is possible to drag a DataForm to the project. It creates a test object album. If the object property is a string, then a text input field is rendered. If the object property is true/false a checkbox is rendered.

How can a picker be rendered which allows for a choice of items? 

I cant see any way to add groups, validators or custom inupt types.

Since I am asking, is it possible to load the picker data dynamically?

### Did you search for the problem in [other open issues in this repo](https://github.com/NativeScript/playground-feedback/issues)?
Yes

### Tell us about the problem
DataForm Picker from VueJS Examples Needed

### Did you try it outside of {N} Playground?
- No

### Which browser are you using?
Chrome

### Are there any errors/warnings logged in your browser console?
NA cant run

### Which platform(s) does your issue occur on?
- Both

### Are there any entries logged in the Device Logs tab?
NA

### Please provide the following information shown in devices tab in the playground:
NA

### Please tell us how to recreate the issue with as much detail as possible.
Add a DataForm to your project and then add an entry that is to act like a Picker

**Comment by VladimirAmiorkov** [comment]
Hi @fwarren ,

The current state of the VueJS support for nativescript-ui-dataform does not support the addition of list (picker) editors. 

Moving this issue to the dedicated Pro UI feedback repository. Closing this issue please follow this one: https://github.com/telerik/nativescript-ui-feedback/issues/784
