### ISSUE TITLE
Playground suggestion : don't change url 

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/playground-feedback#8]
If I have a playground with this url : `https://play.nativescript.org/?template=play-ng&id=iwHWlz` and then I edit the file , 
`url` is changed to **default**

**This is bad.**

Don't take the flow indicators from the user without an explicit user action. 
Not to mention that if a user has many tabs - he won't know on which tab/context he is on.

Also not to mention that a user relies on CTRL+D ( bookmark) to work , and when it does, it will bookmark an empty project (without even knowing it !!!!!)

**Comment by RoyiNamir** [comment]
Is it going to be reolved sometime?

**Comment by vhristov5555** [comment]
We have deployed it to Live. So, from now on the URL shouldn't be changed.
