### ISSUE TITLE
Clean a project

### ISSUE THREAD

**Issue by LeoDupont** [NativeScript/playground-feedback#85]
Hi !
Is it possible to clean a Nativescript Playground project?

I tried so save and fork my project, restart Chrome, quit and restart the Playground and Preview Android apps... but each time I click on "Preview" and scan the QR code, I get old error messages for code that doesn't exist anymore... like incorrect import paths.

**Comment by darind** [comment]
@LeoDupont, reinstalling the Preview app from the Google Play Store should resolve those kind of issues.
