### ISSUE TITLE
Step 7 of the Vue/Weather walkthrough alter code issue

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/playground-feedback#87]
## Please, provide the details below:
On Step 7 of the Weather app walk through, the text for the step *ends* with:

"Your current weather might include terms not handled below, so alter the code below if you find that an image is not displayed. Check the included console.log for the name of the icon that is produced by the API."

But this is the end of the step and there is no code below.

**Comment by cfjedimaster** [comment]
In the same are, "the included console.log" - what included log file? Where is it included?

**Comment by tjvantoll** [comment]
Addressed with https://github.com/NativeScript/playground-tutorials/commit/ab32dd730d94712e280d25c7631146306457148f.

Thanks again @cfjedimaster!
