### ISSUE TITLE
Playground suggestion : format code ?

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/playground-feedback#9]
It will be wonderful to have a `format code` button which will beautify code  : 

![image](https://user-images.githubusercontent.com/2842123/36339100-91355610-13c6-11e8-968e-cbb0e9871e59.png)

**Comment by darind** [comment]
There's a Format Document shortcut in the context menu:

![image](https://user-images.githubusercontent.com/270695/36339119-d56bcaa8-13c6-11e8-9891-77a93bcef611.png)

We will consider adding it as a button in the command toolbar to make it more visible.

**Comment by RoyiNamir** [comment]
(Wow, I didn't see it:-)

Thanks @darind
