### ISSUE TITLE
Saved projects don't show up in the "Projects" tab in playground

### ISSUE THREAD

**Issue by gagata** [NativeScript/playground-feedback#91]
Hi, 
saving my project from the NativeScript Playground won't actually preserve the work (even though I am logged in), and the "Projects" tab persists empty.

Thanks for help!

**Comment by darind** [comment]
@gagata, could you provide some more details. How are you saving the project? If you use the :cloud: button in the playground, are you getting an unique url in the browser containing the `id` parameter? If not, are there any javascript errors logged in the console?

Please note that if you use the <kbd>Ctrl+S</kbd> or the <kbd>Preview</kbd> button it will not persist your changes during page reloads in the browser.
