### ISSUE TITLE
Playground Runtime Version

### ISSUE THREAD

**Issue by sbwrege2z** [NativeScript/playground-feedback#92]
### Did you search for the problem in [other open issues in this repo](https://github.com/NativeScript/playground-feedback/issues)?

Yes.

### Tell us about the problem

It would be nice to have a feature where you could specify the runtime version that the Preview app uses.  I know the Playground is more of a "getting started" tool, but as the sole developer I have found the Playground to be a great way to deploy the app to our graphic designer and other employees (non tech-savvy) for their feedback during development without having to to through the play and app stores (they just need to scan a QR code and viola!).  The latest update from runtime version 4.2.0 to 5.0.0 really messed things up for my app on the iPhone in particular.  There seems to be no convenient way for me to have them go back to the Preview app version 1.16.0 that used the 4.2.0 runtime.  This would be a great feature.  

### Did you try it outside of {N} Playground?

No.  I'm not sure what the best alternatives for getting my app onto their phone in the development stage are.  We are not physically located in the same place.  For Android I suppose I could compile an APK and store it in a shared location, but most of the team has iPhones anyway.  Any alternatives to the Playground for my use case would be welcomed.

### Which browser are you using?

Chrome

### Are there any errors/warnings logged in your browser console?

No.

### Which platform(s) does your issue occur on?

The update from 5,0.0 mostly impacted the iOS version, but there were a few Android problems I found.  One is already been logged as a bug: https://github.com/NativeScript/NativeScript/issues/6511

### Are there any entries logged in the Device Logs tab?

Not relevant.

### Please provide the following information shown in devices tab in the playground:

iPhone 6
iOS 12.1.0
Preview 1.16.0
Runtime 5.0.0

SM-G965U
Android 8.0.0
Preview 1.16.0
Runtime 5.0.0

SM-G920V
Android 7.0
Preview 1.15.1
Runtime 4.2.0

### Please tell us how to recreate the issue with as much detail as possible.

My app is in active development with a lot of the security features yet to be developed (only using internally).  It is not a specific problem with the app.  The main problem is to not be at the mercy of the currently pushed runtime.  A setting to specify the runtime is what I am asking for.  This hasn't been a concern with the minor upgrades, but the push from 4.2 to 5.0 has had a big impact.  In general I wait to use any major updates until they've been in use for a while.

**Comment by darind** [comment]
Unfortunately the NativeScript runtime is currently not designed to be hot swapped without recompiling the application. And such changes are quite difficult to be made to an application that is already deployed in the AppStores.
