### ISSUE TITLE
nativescript-videorecorder javascript

### ISSUE THREAD

**Issue by sprioagustina** [NativeScript/playground-feedback#95]
Hi! are there some sample code to use nativescript-videorecorder plugin on javascript?
I only founded on ts and html, but I need it in js and xml. 

Some news about to record video stream?

thanks!

**Comment by radeva** [comment]
Hi @sprioagustina ,

You better ask in the [nativescript-videorecorder plugin repo](https://github.com/triniwiz/nativescript-videorecorder). 

I'm closing this issue now since it's not related to the NativeScript Playground itself.
