### ISSUE TITLE
Small Typo in the tutorial

### ISSUE THREAD

**Issue by shikhin21** [NativeScript/playground-feedback#96]
In step 13.c of Lesson 3 of the Groceries tutorial, right where it says

Let’s break down how this layout works, starting with the outer structure of the markup.
`<GridLayout rows="auto, *">
  <GridLayout row="0" class="add-bar">...</GridLayout>
  <ListView row="1">...</ListView>
</GridLayout>`

I believe, the code should instead be,
`<GridLayout rows="auto, *">
  <GridLayout row="0" class="add-bar">...</GridLayout>
  <RadListView row="1">...</RadListView>
</GridLayout>`

**Comment by vchimev** [comment]
Thank you for letting us know, @shikhin21! Feel free to open a pull-request in such cases. ;)
